version: '3.8'
services:
  ollama-container-1:
    image: ollama/ollama
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - 11435:11434

  streamlit-app:
    build:
      context: .
    ports:
      - 8501:8501
    depends_on:
      - ollama-container-1
